import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  disableTotalPeriod: false,
  list: [
    {
      title: '무신사',
      position: '커뮤니티 트라이브 인게이지먼트팀 백엔드 개발자',
      startedAt: '2019-10',
      descriptions: [
        '온라인 편집샵 (1700명~, 엔지니어링 250명~)',
        '사용자 Needs 에 맞는 사용성 개선과 신규 비즈니스 로직 구현',
        '레거시 청산 및 기존 비즈니스 로직 유지보수',
        'AWS 인프라 활용 및 Event-Driven 기반 아키텍쳐 설계',
        'DDD(Domain Driven Design) 도메인 주도 설계 도입',
        'ATDD(Acceptance Test Driven Development) 개발 방식 도입',
        'Agile 연구 및 도입(사용자 스토리 기반 정의, 페어 프로그래밍, 회고)',
      ],
      skillKeywords: [
        'Java',
        'Kotlin',
        'Spring',
        'Go',
        'Node.js',
        'TypeScript',
        'AWS RDS',
        'AWS DynamoDB',
        'AWS ElastiCache',
        'Elasticsearch',
        'K8S',
        'Docker',
        'AWS Lambda',
        'AWS Step Functions',
        'Serverless',
        'AWS SNS',
        'AWS SQS',
        'Apache Kafka',
        'AWS CloudWatch',
        'AWS Athena',
        'AWS ECR',
        'AWS EKS',
        'GitHub',
        'ArgoCD',
        'Jenkins',
        'Spinnaker',
        'Kibana',
        'Grafana',
        'Gradle',
        'JUnit5',
        'Kotest',
        'Puppeteer',
        'Agile',
        'A/B Test',
      ],
    },
    {
      title: '한비로',
      position: '개발팀 풀스택 개발자',
      startedAt: '2013-07',
      endedAt: '2019-09',
      descriptions: [
        '그룹웨어 및 웹 호스팅 서비스업 (60명, 개발팀 10명)',
        'CRM 풀스택 개발',
        '레거시 청산 및 기존 비즈니스 유지보수',
        'RDB Schema 모델링 및 아키텍쳐 설계',
      ],
      skillKeywords: [
        'Java',
        'Spring',
        'PHP',
        'MySQL',
        'CentOS',
        'Memcached',
        'Elasticsearch',
        'AngularJS',
        'Vue.js',
        'Javascript',
        'HTML/CSS',
      ],
    },
    {
      title: '에스에스알',
      position: '개발팀 풀스택 개발자',
      startedAt: '2013-04',
      endedAt: '2013-07',
      descriptions: [
        '보안 취약점 진단 솔루션, 정보보안 컨설팅 전문기업 (60명, 개발팀 10명)',
        '악성코드 탐지 모니터링 솔루션 MetiEye 관리서버 구성 및 웹 풀스택 개발',
        '시스템진단 솔루션 SolidStep 관리서버 구성 및 웹 풀스택 개발',
        'RDB Schema 모델링 및 백엔드 아키텍쳐, 서버 인프라 구축',
      ],
      skillKeywords: ['PHP', 'Postgresql', 'Javascript', 'HTML/CSS'],
    },
    {
      title: 'e-Junction, Korea',
      position: '개발팀 풀스택 개발자',
      startedAt: '2011-11',
      endedAt: '2013-04',
      descriptions: [
        '스티커 사진 관련 온라인 서비스 개발 (8명)',
        '제휴된 스티커 사진 매장에서 촬영된 사진을 온라인에서 제공하는 서비스 개발',
        'RDB Schema 모델링 및 백엔드 아키텍쳐, 서버 인프라 구축',
      ],
      skillKeywords: ['PHP', 'MySQL', 'CentOS', 'Javascript', 'HTML/CSS'],
    },
    {
      title: '클라우드웹',
      position: '개발팀 웹 개발자',
      startedAt: '2010-02',
      endedAt: '2011-11',
      descriptions: [
        'IT 스타트업 (10명)',
        '4대 포털사이트의 검색 결과 레이아웃 재편집 도구 개발',
        '여성의류 쇼핑몰 개발',
      ],
      skillKeywords: ['PHP', 'MySQL', 'Javascript', 'HTML/CSS'],
    },
  ],
};

export default experience;
